# Generated by Django 2.2.6 on 2019-11-09 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CANDIDAT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionClass', models.CharField(max_length=50, verbose_name='Section')),
                ('number', models.IntegerField(verbose_name='numero de la classe')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInscription', models.DateField(verbose_name="date d'inscription")),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('dateInscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('sectionProf', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterNr', models.IntegerField(verbose_name='Trimestre numero')),
            ],
        ),
        migrations.CreateModel(
            name='School_subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolYear', models.DateTimeField(default=django.utils.timezone.now, verbose_name='année scolaire')),
                ('inscriptionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Inscription')),
                ('quarterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.ClassRoom')),
                ('professorFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('rue', models.CharField(max_length=100)),
                ('cp', models.IntegerField(verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100)),
                ('classroomFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.ClassRoom')),
                ('inscriptionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Inscription')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterTeaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Quarter')),
                ('teachesFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Teaches')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classRooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.ClassRoom')),
                ('quarters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professorFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Professor')),
                ('school_subjectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.School_subjects')),
            ],
        ),
    ]
