# Generated by Django 2.2.6 on 2020-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0008_auto_20200120_1407'),
        ('SCHOOL', '0002_classroom_nombreplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='quarterclass',
            name='classRooms',
        ),
        migrations.RemoveField(
            model_name='quarterclass',
            name='quarters',
        ),
        migrations.RemoveField(
            model_name='quarterteaches',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='quarterteaches',
            name='teachesFK',
        ),
        migrations.RemoveField(
            model_name='years',
            name='quarterFK',
        ),
        migrations.AddField(
            model_name='teaches',
            name='school_subjectFK',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.School_subjects'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.IntegerField(verbose_name='nombre de classe'),
        ),
        migrations.DeleteModel(
            name='Enseigne',
        ),
        migrations.DeleteModel(
            name='Quarter',
        ),
        migrations.DeleteModel(
            name='QuarterClass',
        ),
        migrations.DeleteModel(
            name='QuarterTeaches',
        ),
        migrations.AddField(
            model_name='classsection',
            name='currentYears',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Years'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Professor'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='sectionRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.ClassRoom'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Student'),
        ),
    ]
