# Generated by Django 2.2.6 on 2020-01-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCHOOL', '0003_auto_20200120_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='intitule',
            field=models.CharField(max_length=20, null=True, verbose_name='Intitulé'),
        ),
    ]
