# Generated by Django 2.2.6 on 2020-01-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCHOOL', '0004_classsection_intitule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='years',
            name='inscriptionFK',
        ),
    ]
