# Generated by Django 2.2.6 on 2020-02-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0022_auto_20200206_2014'),
        ('SCHOOL', '0005_remove_years_inscriptionfk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal_de_classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_du_jour', models.DateField(auto_now_add=True, verbose_name='date du jour')),
                ('intitule_du_devoir', models.CharField(max_length=50, verbose_name='intitule du devoir')),
                ('detail_du_devoir', models.TextField(null=True, verbose_name='devoir')),
                ('note_de_comportement', models.TextField(null=True, verbose_name='note de comportement')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Years')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Professor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Student')),
            ],
        ),
    ]
