# Generated by Django 2.2.6 on 2020-02-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCHOOL', '0006_journal_de_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='student',
        ),
        migrations.AlterField(
            model_name='journal_de_classe',
            name='annee_scolaire',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='SCHOOL.Years'),
        ),
    ]
