# Generated by Django 2.2.6 on 2019-11-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=2)),
                ('dateNaissance', models.DateField()),
                ('ClassePrecedente', models.IntegerField(default=0, verbose_name='Classe précédente')),
                ('langueMaternelle', models.CharField(max_length=50, verbose_name='Langue maternelle')),
                ('repasChaud', models.BooleanField(default=False, verbose_name='Repas chaud')),
                ('XtraScolaire', models.BooleanField(default=False, verbose_name='Sortie extra scolaire')),
                ('AccordPedagogique', models.BooleanField(default=False, verbose_name='Accord pédagogique')),
                ('AccordImage', models.BooleanField(default=False, verbose_name='Accord diffusion image')),
                ('GardeParental', models.CharField(max_length=50, verbose_name='Garde parental')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField(verbose_name='date de naissance')),
                ('rue', models.CharField(max_length=70, verbose_name='Rue, numero')),
                ('cp', models.IntegerField(verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('dateInscription', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('students', models.ManyToManyField(to='CANDIDAT.Student')),
            ],
        ),
    ]
