# Generated by Django 2.2.6 on 2019-11-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Nationalite',
            field=models.CharField(max_length=300, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='student',
            name='Nationalite',
            field=models.CharField(max_length=300, null=True, verbose_name='Nationalité'),
        ),
    ]
