# Generated by Django 2.2.6 on 2019-11-21 13:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0002_auto_20191121_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
