# Generated by Django 2.2.6 on 2019-12-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0003_parent_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Student', verbose_name='student'),
        ),
    ]
