# Generated by Django 2.2.6 on 2019-12-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0005_auto_20191223_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
    ]
