# Generated by Django 2.2.6 on 2020-01-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0006_remove_parent_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('M', 'Maternelle'), ('P', 'Primaire')], default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='ClassePrecedente',
            field=models.IntegerField(default=0, verbose_name='Classe'),
        ),
    ]
