# Generated by Django 2.2.6 on 2020-01-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0007_auto_20200119_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('Maternelle 1', 'Maternelle 1'), ('Maternelle 2', 'Maternelle 2'), ('Maternelle 3', 'Maternelle 3'), ('Primaire', 'Primaire')], default=False, max_length=50),
        ),
    ]
