# Generated by Django 2.2.6 on 2020-02-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0008_auto_20200120_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_Id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Parent'),
        ),
    ]
