# Generated by Django 2.2.6 on 2020-02-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0009_student_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_Id',
            new_name='parent',
        ),
    ]
