# Generated by Django 2.2.6 on 2020-02-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0010_auto_20200202_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='Parent',
        ),
    ]
