# Generated by Django 2.2.6 on 2020-02-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0011_auto_20200202_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Parent',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Parent'),
        ),
    ]
