# Generated by Django 2.2.6 on 2020-02-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0014_auto_20200202_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='IdParentFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Parent'),
        ),
    ]
