# Generated by Django 2.2.6 on 2020-02-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0015_auto_20200202_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='IdParentFK',
        ),
    ]
