# Generated by Django 2.2.6 on 2020-02-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0016_remove_student_idparentfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Id_parentFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Parent'),
        ),
    ]
