# Generated by Django 2.2.6 on 2020-02-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0017_student_id_parentfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Id_parentFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CANDIDAT.Parent'),
        ),
    ]
