# Generated by Django 2.2.6 on 2020-02-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CANDIDAT', '0023_student_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='presence',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
